name: Build, Push

on:
  push:
    branches: [ main ]
jobs:
  build_and_push:
    name: Push docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          logout: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (labels, tags, etc.) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ksoochoi/fastapi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ksoochoi/fastapi:latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy_infrastructure:
    name: Deploy Azure Infrastructure with Terraform
    runs-on: ubuntu-latest
    needs: build_and_push  # Run after the Docker image is pushed
    steps:
      # 1. check out GitHub repository
      - name: Checkout the repository
        uses: actions/checkout@v2

      # 2. install terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      # 3. sign in to Azure (using credentials stored in GitHub Secrets)
      - name: 'Azure Login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4. Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # 5. Apply Terraform (Apply)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_admin_username: ${{ secrets.TF_VAR_ADMIN_USERNAME }}
          TF_VAR_admin_password: ${{ secrets.TF_VAR_ADMIN_PASSWORD }}
      